### ISSUE TITLE
Long upload logs can't be read properly

### ISSUE THREAD

**Issue by glantucan** [teejee2008/baqpaq#1]
Using baqpaq under Pop!_OS 20.04

Not sure if it happens for all logs, but after a successful scheduled upload the log entry appears with several lines messed up. 
![image](https://user-images.githubusercontent.com/1677172/89737871-71df3c80-da6c-11ea-8b44-f505e9eb5614.png)
Also if I try to open  that log the program hangs for a long time and ends up telling me that the text editor is not responding and asking whether I want to force quit it.

**Comment by glantucan** [comment]
Ok, I think this info may be of use. It seems the output of whatever command line program it's being used to make the upload is being dumped into the log file on one single line. In this case it's a really log line as it is uploading 12gb of data. Gedit it's having difficulties parsing it. I managed to find the log file and open it on vscode.
[2020-08-09_15-17-01_upload.0.log](https://github.com/teejee2008/baqpaq/files/5048131/2020-08-09_15-17-01_upload.0.log)

**Comment by glantucan** [comment]
It seems it only happens with upload logs, so I changed the title

**Comment by teejee2008** [comment]
This will be fixed in the next update

**Comment by teejee2008** [comment]
Fixed in v20.08.1

**Comment by teejee2008** [comment]
Run `baqpaq schedule-cron` after installing v20.08.1. It will add the `--no-progress` option to scheduled tasks.
