### ISSUE TITLE
Create logs have their file entries truncated

### ISSUE THREAD

**Issue by glantucan** [teejee2008/baqpaq#2]
At first I thought it was a presentation problem in the program but the truncated data is on the log file.
The log isn't very useful if it informs you on a failed backap of a file you can't find
![image](https://user-images.githubusercontent.com/1677172/89762958-6bdb7100-dae9-11ea-825c-6d4eb1d291a2.png)
[2020-08-10_00-30-02_create.0.log](https://github.com/teejee2008/baqpaq/files/5049671/2020-08-10_00-30-02_create.0.log)

**Comment by teejee2008** [comment]
By default, Borg outputs the progress info in this truncated format. This will be fixed in the next update.

**Comment by teejee2008** [comment]
Fixed in v20.08.1

**Comment by teejee2008** [comment]
The truncated lines show progress while the task is running and is not useful after operation is complete. The log will now display only stats, and error messages with full paths for any files that were skipped due to permission issues.

**Comment by teejee2008** [comment]
Run `baqpaq schedule-cron` after installing v20.08.1. It will add the `--no-progress` option to scheduled tasks.
