### ISSUE TITLE
Adding dot folders and files not possbile with the add buttons.

### ISSUE THREAD

**Issue by AimeelouDestiny** [teejee2008/baqpaq#3]
When using the Add folder(s) and Add file(s) button's in Sources include and exclude it's currently not possible to add dot folders or files. I back up many dot folder's and file's in Home (and Config) which are profile's or configuration file's for apps I use and need backed up in case they are damaged or I have to re-install Linux Mint. Is it possible you could add ability for Bacpaq to allow adding of dot folder's and file's, thank you :o)

**Comment by teejee2008** [comment]
Dot folders and files are hidden by default in the GTK selection dialog. Right-click in the empty space and select "Show hidden files".

![image](https://user-images.githubusercontent.com/12488854/102900859-e6060400-4492-11eb-9eb6-e281254852da.png)

**Comment by AimeelouDestiny** [comment]
Yes I know, but I have already have these options enabled, is first thing I do when I install an OS, I tried both Linux Mint 19.3 and 20.0 which I have  both installed, LM 20.0 works normally, was only LM 19.3 not working correctly, so I tried resetting Cinnamon to default, all seems to be working correctly now, possible something was corrupted with it, but its working okay now, so thanks for all your help, issue is fixed :o)
