### ISSUE TITLE
Data integrity error: Segment entry checksum mismatch

### ISSUE THREAD

**Issue by timrichardson** [teejee2008/baqpaq#5]
I get this error suddenly when making snapshots. 

Data integrity error: Segment entry checksum mismatch

How do I fix it? My backup is large and I would like to avoid having to start again (due to cloud upload)

Validate data shows 

Starting repository check
Data integrity error: Segment entry checksum mismatch [segment 4740, offset 254233335]
Validatoin complete with 43 errors.

**Comment by timrichardson** [comment]
I opened a terminal in the backup directory and did\

`borg check . --repair
`
which may have fixed the problem. No more validation errors, anyway.

**Comment by teejee2008** [comment]
Yes "check --repair" is what you need. If the validation is successful then there is nothing to worry about.
I'll add a repair action in the GUI.
