### ISSUE TITLE
window / dialog resize and save

### ISSUE THREAD

**Issue by Kodiman** [teejee2008/baqpaq#6]
Hi, Baqpaq is excellent. 

Suggestion... The content in "Manage Profiles" window/dialog is truncated when using large fonts for accessibility. Please make it automatically resize to show all content and/or then save any user specified window/dialog resize. The same for any other windows dialogs, etc. Thanks

**Comment by teejee2008** [comment]
Gtk windows are supposed to resize automatically to fit the contents. Could you please share a screenshot of the issue?

**Comment by Kodiman** [comment]
![Screenshot_20220605_104839](https://user-images.githubusercontent.com/9492508/172058960-149ab4fc-5b85-492d-b5b2-066a18b2d51c.png)
![Screenshot_20220605_104758](https://user-images.githubusercontent.com/9492508/172058962-b03ede11-5aef-491f-8eb7-292cd85078dc.png)

this is running on KDE Plasma 5.18.8. it does not auto resize. and it does nor save resize. thanks

**Comment by teejee2008** [comment]
Thanks for the screenshot. It will be fixed in the next update.

**Comment by teejee2008** [comment]
This was fixed in v22.08. Closing.
